language: node_js

node_js:
  - 0.10
  - 0.12
  - 4
  - 5

before_install:
  - npm install -g gulp
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"

script:
  - gulp

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/fb4976f83539730820f1
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
